another try

diff --git a/bin/rollback-deployment b/bin/rollback-deployment
--- a/bin/rollback-deployment
+++ b/bin/rollback-deployment
@@ -2,9 +2,15 @@
 
 echo "Rolling back deployments"
 
-for index in "${!DEPLOYMENTS[@]}"
+if [ -z "$1" ]
+then
+  echo "ERROR: No deployment specified"
+  exit 1
+fi
+
+for index in "${1}"
 do
-  DEPLOYMENT=${DEPLOYMENTS[$index]##*/}
+  DEPLOYMENT=${1[$index]##*/}
   echo "Rolling back deployment for $DEPLOYMENT"
   kubectl --namespace="${NAMESPACE:=default}" rollout undo deployment/"${DEPLOYMENT}"
 done
